openapi: 3.0.0
info:
  title: SportLogic API (v2)
  version: '2.0'
  description: SportLogic API - version 2.
  contact:
    email: developer@sportlogic.com.au
    url: www.sportlogic.com.au
servers:
  - url: 'https://api-v2.sportlogic.net.au'
paths:
  '/programs/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: program id
    get:
      summary: Get Program
      tags:
        - Program Domain
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./Program.json
              examples:
                example-1:
                  value:
                    id: 0
                    name: string
                    active: true
                    description: string
        '404':
          description: Not Found
      operationId: get-domain-programs-id
      description: Get a Program
      security:
        - API Key: []
  /contacts:
    get:
      summary: Get Contacts
      tags:
        - Contact Domain
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./Contact.json
              examples: {}
      operationId: get-domain-contacts
      description: Retrieve contacts
      parameters:
        - schema:
            type: number
          in: query
          name: skip
        - schema:
            type: number
          in: query
          name: limit
      security:
        - API Key: []
    parameters: []
  '/contacts/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Contact ID
    get:
      summary: Get Contact
      tags:
        - Contact Domain
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./Contact.json
        '404':
          description: Not Found
      operationId: get-domain-contacts-id
      description: Get a single Contact.
      security:
        - API Key: []
  '/members/{id}/card':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: membership id
    get:
      summary: Get member card
      tags:
        - Membership Domain
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./MembershipCard.json
        '404':
          description: Not Found
      operationId: get-domain-members-id-card
      description: Get member card details
      security:
        - API Key: []
    put:
      summary: Update member card
      operationId: put-domain-members-id-card
      responses:
        '200':
          description: Updated
        '201':
          description: Created
      description: Update member card details
      security:
        - API Key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./MembershipCard.json
      tags:
        - Membership Domain
  /members:
    get:
      summary: Get members
      tags:
        - Membership Domain
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./Membership.json
      operationId: get-domain-members
      description: ''
      security:
        - API Key: []
    parameters: []
  /venue-platform-service/venues:
    get:
      summary: Get Venues
      tags:
        - Venue Platform
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./VPVenue.json
      operationId: get-venue-platform-service
      parameters:
        - schema:
            type: string
          in: query
          name: siteCode
          description: Site Code e.g. "tennisvenues.com.au"
          required: true
        - schema:
            type: string
          in: query
          name: sportType
          description: 'Sport Type e.g. "Squash", "Badminton"'
        - schema:
            type: integer
          in: query
          name: skip
          description: Number of records to skip.
        - schema:
            type: integer
          in: query
          name: limit
          description: Number of records to fetch.
      security:
        - API Key: []
    parameters: []
  /resources:
    get:
      summary: Get Resources
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./Resource.json
      operationId: get-resources
      security:
        - API Key: []
      parameters:
        - schema:
            type: integer
          in: query
          name: venueId
          description: Get resources by venue
        - schema:
            type: string
          in: query
          name: webEnabledOnly
          description: Filter resources by web enabled
    parameters: []
components:
  schemas: {}
  securitySchemes:
    API Key:
      name: apiKey
      type: apiKey
      in: header
security:
  - API Key: []
tags:
  - name: Contact Domain
  - name: Membership Domain
