openapi: 3.0.0
info:
  title: SportLogic API (v2)
  version: '2.0'
  description: SportLogic API - version 2.
  contact:
    email: developer@sportlogic.com.au
    name: Developer
    url: www.sportlogic.com.au
servers:
  - url: 'https://api-v2.sportlogic.net.au'
paths:
  /service/auth/request-api-access-token:
    get:
      summary: Request API Access Token
      tags:
        - Authentication Service
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                description: access token
      operationId: get-service-auth-request-api-access-token
      description: Request API access token.
  '/domain/programs/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: program id
    get:
      summary: Get Program
      tags:
        - Program Domain
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./Program.v2.json
              examples:
                example-1:
                  value:
                    id: 0
                    name: string
                    active: true
                    description: string
        '404':
          description: Not Found
      operationId: get-domain-programs-id
      description: Get a Program
      security:
        - API Key: []
        - Access Token: []
  /domain/contacts:
    get:
      summary: Get Contacts
      tags:
        - Contact Domain
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./Contact.v2.json
              examples: {}
      operationId: get-domain-contacts
      description: Retrieve contacts
      parameters:
        - schema:
            type: number
          in: query
          name: skip
        - schema:
            type: number
          in: query
          name: limit
      security:
        - API Key: []
    parameters: []
  '/domain/contacts/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Contact ID
    get:
      summary: Your GET endpoint
      tags:
        - Contact Domain
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./Contact.v2.json
        '404':
          description: Not Found
      operationId: get-domain-contacts-id
      description: Get a single Contact.
      security:
        - API Key: []
components:
  schemas: {}
  securitySchemes:
    API Key:
      name: api_key
      type: apiKey
      in: header
    Access Token:
      name: access_token
      type: apiKey
      in: header
security:
  - API Key: []
tags:
  - name: Contact Domain
